### ISSUE TITLE
Missing Authentication Token

### ISSUE THREAD

**Issue by anjaneyach** [function61/lambda-atomic-counter#1]
i got below error message , but we have Authentication type none 
{"message":"Missing Authentication Token"} #bug #

**Comment by joonas-fi** [comment]
I don't see `Missing Authentication Token` string mentioned in this repository, so I believe this is an issue with API Gateway.

I think I've encountered same kind of problem before, where the issue was that I forgot to "deploy" the API Gateway API after making a change. Try deploying the API and see if that fixes it?

**Comment by anjaneyach** [comment]
Thanks joonas-fi , now its working , the way calling api is changed  
from https://REDACTED.execute-api.us-east-1.amazonaws.com/prod/counter/increment
to 
https://REDACTED.execute-api.us-east-1.amazonaws.com/prod/counter/increment?counter=mycounter.

**Comment by joonas-fi** [comment]
But isn't your second URL the same as in the README: https://github.com/function61/lambda-atomic-counter#how ?

Do you mean that the URL's "/prod/counter" part is confusing in the way that people expect "counter" to be the counter's name?

**Comment by joonas-fi** [comment]
Closing since the actual issue is resolved, but we can still continue the discussion :)

**Comment by anjaneyach** [comment]
@joonas-fi yes, in my url i missed '?counter=mycounter.' this part 
after added this , its working good
